version: "3.8"
services:
  callboard:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  redis:
    image: redis:6.0.9
  mongo:
    image: mongo:4.4
    volumes:
      - ./db:/data/db
    expose:
      - "27017"